# Generated by Django 4.2 on 2023-04-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(max_length=255)),
                ('dateofborn', models.DateField(blank=True, null=True)),
                ('dateofdied', models.DateField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, max_length=50, null=True)),
                ('notable_work', models.TextField(blank=True, max_length=255, null=True)),
                ('article_about', models.TextField(blank=True, max_length=8000, null=True)),
                ('known_for', models.TextField(blank=True, max_length=255, null=True)),
                ('article_year', models.IntegerField(blank=True, null=True)),
                ('medium', models.TextField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, max_length=255, null=True)),
                ('designed', models.TextField(blank=True, max_length=255, null=True)),
                ('developer', models.TextField(blank=True, max_length=255, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARTICLES_HUB.articlecategory')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARTICLES_HUB.articletype')),
            ],
        ),
    ]
