# Generated by Django 4.2 on 2023-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES_HUB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='developer',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
