# Generated by Django 4.2 on 2023-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES_HUB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dateofborn',
        ),
        migrations.RemoveField(
            model_name='article',
            name='dateofdied',
        ),
        migrations.AddField(
            model_name='article',
            name='dimensions',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='year_of_born',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='year_of_died',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_about',
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_year',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='designed',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='developer',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='known_for',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='medium',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='nationality',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='notable_work',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
