# Generated by Django 4.2 on 2023-04-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES_HUB', '0002_remove_article_dateofborn_remove_article_dateofdied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_about',
            field=models.TextField(max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_year',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='designed',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='developer',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='dimensions',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='known_for',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='medium',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='nationality',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='notable_work',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='year_of_born',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='year_of_died',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
